spring:
  datasource:

    url: "jdbc:mysql://anonymous-db.chusisqoid5w.ap-northeast-2.rds.amazonaws.com:3306/anonymous?serverTimezone=Asia/Seoul&character_set_server=utf8mb4&collation-server=utf8mb4_general_ci&allowMultiQueries=true"
    username: "shpark"
    password: ${MYSQL_SECRET}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      uri-encoding: UTF-8
  devtools:
    restart:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug

