spring:
  datasource:
    url: "jdbc:mysql://anonymous-db.cbmw802mu38i.ap-northeast-2.rds.amazonaws.com:3306/anonymous?serverTimezone=Asia/Seoul&character_set_server=utf8mb4&collation-server=utf8mb4_general_ci&allowMultiQueries=true"
    username: "park7614"
    password: ${MYSQL_SECRET}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      uri-encoding: UTF-8
  devtools:
    restart:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug