spring:
  datasource:
    url: "jdbc:mysql://localhost/board"
    username: "root"
    password: "elio1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug